### PR TITLE
Fix zobrist keys

### LINKED ISSUE #20: `ZobristTable::hands` is too small
MAX_HAND_NUM is 18. For a position where someone has all 18 pawns in hand, this line probably causes out-of-bounds accesses.
https://github.com/sugyan/yasai/blob/a7011ec7c1216bb2cf07d929c2c9722f062154f0/src/zobrist.rs#L52

### PR DESCRIPTION
**Pull request by sugyan**
Fixes #20

### CODE REVIEW

File: src/zobrist.rs [hunk 1]
```diff
@@ -107,11 +107,84 @@ mod tests {
...
             PartialPosition::from_usi("sfen 9/9/9/9/9/9/9/9/9 b 2R2B4G4S4N4L18P 1")
                 .expect("failed to parse"),
         );
-        assert_ne!(0, pos.key());
+        let all_white_hands = Position::new(
+            PartialPosition::from_usi("sfen 9/9/9/9/9/9/9/9/9 b 2r2b4g4s4n4l18p 1")
+                .expect("failed to parse"),
+        );
+        assert_eq!(0, all_black_hands.keys().0);
+        assert_eq!(0, all_black_hands.keys().0);
```
Comment (koba-e964) [inline src/zobrist.rs:119]: Probably a typo?
```suggestion
        assert_eq!(0, all_white_hands.keys().0);
```

Comment (sugyan) [reply src/zobrist.rs:119]: Oops ... Thank you for pointing it out 🙇
